project/products/api/urls.py
from django.urls import re_path
from rest_framework import routers

from .views import ItemAPIView, ItemRudView # ItemPrice

app_name = 'products_api'

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    re_path(r'^items/$', ItemAPIView.as_view(), name='list_create_item_api'),
	re_path(r'^item/(?P<pk>\d+)/$', ItemRudView.as_view(), name='rud_item_api'),
	# re_path(r'^item/price/$', ItemPrice.as_view(), name='price'),
]

project/products/urls.py
from django.urls import re_path

from .views import item_list_view, item_detail_view

app_name = 'products'


urlpatterns = [
    re_path(r'^', item_list_view, name='item_list'),
    re_path(r'^detail/(?P<item_id>[0-9]+)/$', item_detail_view, name='item_detail'),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import include, re_path
# from rest_framework import routers

from products.api import views



urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^api/', include('products.api.urls',  namespace='products_api')),
    re_path(r'^', include('products.urls',  namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project/products/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from rest_framework.reverse import reverse

'''
https://stackoverflow.com/questions/2307674/in-django-what-is-a-sku
Stock keeping unit
'''


class Item(models.Model):
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name    = models.CharField(max_length=255)
    qty     = models.PositiveSmallIntegerField(default=0)
    price   = models.DecimalField(max_digits=5, decimal_places=2)
    # sku     = models.CharField(max_length=255, unique=True)
    created = models.DateTimeField(auto_now_add=True,)
    update  = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)


    def get_url_api(self, request=None):
        return reverse('products_api:rud_item_api', kwargs={'pk': self.pk}, request=request)

    @property
    def in_stock(self):
        return int(self.qty > 0)

    @property
    def soled_item(self):
        return self.soled_item

    # Use for attribute owner in permission.py line 17
    @property
    def owner(self):
        return self.user

project/products/api/views.py
from django.db.models import Q
from rest_framework import generics
from rest_framework import mixins
from rest_framework import permissions
from rest_framework import filters
from rest_framework.filters import SearchFilter, OrderingFilter


from products.models import Item
from .permissions import IsOwnerOrReadOnly
from .serializers import ItemSerializer


'''
Endpoint 
Using mixins help to create, list update all in one
'''


class ItemAPIView(mixins.CreateModelMixin, generics.ListAPIView):
    lookup_field = 'pk'
    serializer_class = ItemSerializer
    permission_classes = [IsOwnerOrReadOnly]
    
    queryset = Item.objects.all()
    filter_backends = [SearchFilter, OrderingFilter]
    # Search only for name of the item
    search_fields = ['name']


    # This help to create new item without adding username
    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def get_serializer_context(self, *args, **kwargs):
    	return {'request': self.request}



class ItemRudView(generics.RetrieveUpdateDestroyAPIView):
    lookup_field = 'pk'
    serializer_class = ItemSerializer
    permission_classes = [IsOwnerOrReadOnly]

    def get_queryset(self):
        return Item.objects.all()


    def get_serializer_context(self, *args, **kwargs):
    	return {'request': self.request}

project/products/views.py
from django.shortcuts import render, get_object_or_404, redirect
# from django.utils import timezone
from django.http import Http404

from .models import Item


def item_list_view(request):
    template_name = 'index.html'
    queryset = Item.objects.all().order_by('-created')

    context = {'items': queryset}
    return render(request, template_name, context)


def item_detail_view(request, item_id):
    template_name = 'details.html'
    try:
        item_obj = get_object_or_404(Item, pk=item_id)
    except Item.DoesNotExist:
        raise Http404('Item does not exist')

    context = {
        'obj': item_obj,
    }
    return render(request, template_name, context)

project/products/templates/details.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
	<div class="row">
      <div class="col-md-4">
			
			<h4 class="my-0 font-weight-normal">Name: {{ obj.name }}</h4>
		
				<p>Quantity: {{ obj.qty }}</p>
				<p>Price: {{ obj.price }}</p>
		
				<a href="{% url 'products:item_list' %}" type="button" class="btn btn-lg btn-block btn-outline-primary" >
				back
			</a>
			
		</div>
	</div>
</div>
{% endblock content %}

project/products/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
	<div class="row text-center">
		{% for obj in items %}
		<div class="col-md-4 shadow-sm">
			<div class="card-header">
				<h4 class="my-0 font-weight-normal">{{ obj.name }}</h4>
			</div>
			<div class="card-body">
				<ul class="list-unstyled mt-3 mb-4">
					<li>{{ obj.name }}</li>
					<li>Quantity: {{ obj.qty }}</li>
					<li>Price: {{ obj.price }}</li>
				</ul>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock content %}

project/products/templates/items.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
	<div class="card-deck mb-3 text-center">
		{% for item in items %}
		<div class="card mb-4 shadow-sm">
			<div class="card-header">
				<h4 class="my-0 font-weight-normal">{{ item.name }}</h4>
			</div>
			<div class="card-body">
				<!-- <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1> -->
				<ul class="list-unstyled mt-3 mb-4">
					<li></li>
					<li>{{ item.sku }}</li>
					<li>{{ item.qty }}</li>
					<li>{{ item.price }}</li>
				</ul>
				<button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>
			</div>
		</div>
		{% endfor %}
		<!-- <div class="card mb-4 shadow-sm">
			<div class="card-header">
				<h4 class="my-0 font-weight-normal">Pro</h4>
			</div>
			<div class="card-body">
				<h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
				<ul class="list-unstyled mt-3 mb-4">
					<li>20 users included</li>
					<li>10 GB of storage</li>
					<li>Priority email support</li>
					<li>Help center access</li>
				</ul>
				<button type="button" class="btn btn-lg btn-block btn-primary">Get started</button>
			</div>
		</div>
		<div class="card mb-4 shadow-sm">
			<div class="card-header">
				<h4 class="my-0 font-weight-normal">Enterprise</h4>
			</div>
			<div class="card-body">
				<h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
				<ul class="list-unstyled mt-3 mb-4">
					<li>30 users included</li>
					<li>15 GB of storage</li>
					<li>Phone and email support</li>
					<li>Help center access</li>
				</ul>
				<button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
			</div>
		</div> -->
	</div>
{% endblock content %}

project/templates/base.html
{% include 'header.html' %}

{% include 'navbar.html' %}


{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1 class="display-4">Pricing</h1>
	<p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
</div>


{% endblock content %}

{% include 'footer.html' %}

project/templates/header.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Jekyll v4.1.1">
        <title>RecyclaBox</title>
        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <meta name="theme-color" content="#563d7c">
        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
            }
        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
        </style>
        <!-- Custom styles for this template -->
        <link href="{% static 'pricing.css' %}" rel="stylesheet">
    </head>
    <body>

project/templates/navbar.html
{% load static %}

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
	
	<h5 class="my-0 mr-md-auto font-weight-normal">
		<a class="p-2 text-dark" href="{% url 'products:item_list' %}">
			RecycalBox
		</a>
	</h5>
	<nav class="my-2 my-md-0 mr-md-3">
		<a class="p-2 text-dark" href="{% url 'products:item_list' %}">Products</a>
		{% if user.is_authenticated %}
			<a class="p-2 text-dark" href="{% url 'products_api:list_create_item_api' %}" target="_blank">
				API
			</a>
		{% endif %}
		<a class="p-2 text-dark" href="#">Sold</a>
	</nav>

</div>